### ISSUE TITLE
Detached Routers example throwing error TypeError: Cannot call method 'push' of undefined on line 77 of express-ws-routes.js

### ISSUE THREAD

**Issue by narendra-agashe** [amekkawi/express-ws-routes#1]
First of all thanks a lot for writing this library which supports express detached routing.

I am trying to put it to use and running into an issue. My application is running on NodeJS 0.10.35 with Express 4 and above.

I am importing the express-ws-routes module in my code as shown below

``` javascript
var express = require('express');
var expressWs = require('express-ws-routes')();
```

Then I am trying to add your example in the code 

``` javascript
var router = express.Router();

    router.websocket('/sub/path', function(info, cb, next) {
      cb(function(socket) {
        console.info('came here');
        socket.send('connected!');
      });
    });
```

Rest of my router code is like this 

``` javascript
router.post('/submitReport', isLoggedIn, reportsRoute.submitReport);
router.get('/getProductList', searchRoute.getProductList);
```

When i include the example my server crashes and throws TypeError: Cannot call method 'push' of undefined on line 77 of express-ws-routes.js.

What could I be doing wrong here, could you please help..?

Regards,
Narendra

**Comment by amekkawi** [comment]
Hi Narenda. I'm sorry you're encountering this issue.

What is the exact version of express 4 you are using?

**Comment by amekkawi** [comment]
I'm guessing you are using a version prior to 4.5.0. I'll take a look at the older versions to see if they can be supported.

**Comment by narendra-agashe** [comment]
Sorry for the late reply, your guess was perfect i was on express version prior to 4.5.0, the moment i upgraded to ExpressJS version < 4.5.0 everything started working fine.

is there any way of closing the socket..? i am trying to close the socket after my processing is done.

**Comment by amekkawi** [comment]
Sorry! I missed the question in your last message.

You should be able to close the websocket using `socket.close()`.

See https://github.com/websockets/ws/blob/master/doc/ws.md#websocketclosecode-data

**Comment by amekkawi** [comment]
Closing this issue since supporting versions prior to 4.5.0 would require some hacky ducktyping checks which I'd rather not do.

**Comment by amekkawi** [comment]
_Published v1.1.0 (d93e77395c930d36a158bb6875cc273c92a5e89c) which adds peer dependency for express@^4.5.0_
