### ISSUE TITLE
how to get the clients msg

### ISSUE THREAD

**Issue by masonwu311** [amekkawi/express-ws-routes#3]
app.ws('/ws/chat/:uid', function(info, cb, next) {
    // `info` is the same as ws's verifyClient
    console.log(
        'ws req from %s using origin %s',
        info.req.originalUrl || info.req.url,
        info.origin
    );
     console.log(info.req.params.uid);
    //console.log(info.req.socket.server.verifyClient);
    // Accept connections by passing a function to cb that will handle the connected websocket
    cb(function(socket) {
      console.log(socket.route.stack);
        socket.send(info.req.params.uid);
    });
});

**Comment by masonwu311** [comment]
i have resovle : app.ws('/ws/chat/:uid', function(info, cb, next) {
    // `info` is the same as ws's verifyClient
    console.log(
        'ws req from %s using origin %s',
        info.req.originalUrl || info.req.url,
        info.origin
    );
     console.log(info.req.params.uid);
    //console.log(info.req.socket.server.verifyClient);
    // Accept connections by passing a function to cb that will handle the connected websocket
    cb(function(socket) {
      socket.on('message', function(msg) {
        console.log(msg);
        socket.send(msg);
      });
      console.log(socket.route.stack);

```
});
```

});

**Comment by amekkawi** [comment]
Glad it got resolved :)
