### ISSUE TITLE
Question: How to Send to Specific Routes?

### ISSUE THREAD

**Issue by 360disrupt** [amekkawi/express-ws-routes#4]
I'm using `ws` for my websocket communication. The receiving part is like in a usual express REST api. But I don't understand the sending part.

So if this `server A` who want to send:

```
createServer: (options)->
   @.wss = new WebSocketServer({ port: process.env.PORT_WEBSOCKET})
   self = @
   logger.info("Websocket listening on #{process.env.PORT_WEBSOCKET}")
   ...

   @.wss.on 'connection', (ws) ->
       ....


send: (data)->
   @.ws.send JSON.stringify data
```

And this is `server B` who listens:

```
module.exports = (app)->
  app.websocket('/routeX', (info, cb, next) ->
    console.log(
      'ws req from %s using origin %s',
      info.req.originalUrl || info.req.url,
      info.origin
    )

```

Do I need an own connection for each route?
`ws1 = new WebSocket("ws://.../routeX")`
`ws2 = new WebSocket("ws://.../routeY")`
`ws3 = new WebSocket("ws://.../routeZ")`

Or can server A specify the route and just connect to a more common endpoint? And how would this be done?
`ws = new WebSocket("ws://myincredibleapi.com:7000")`

**Comment by amekkawi** [comment]
Sorry for the late reply! Might as well answer this though 😄 

Just like normal HTTP requests, the routes (i.e. "/routeX") are matched against the path in the HTTP request header. With websockets however, that initial request is "upgraded" into a two-way socket connection. Both are senders and receivers are this point.

This library allows to you separate parts of your node server that handle websocket connections in different ways. For example, you may have a single server that handles completely separate applications under different paths (e.g. `/finance-app` and `/forcasting-app`).

Once the websocket connection is established, the role of this library ends and it's up to the server/client code to handle how communication will work.

See https://en.wikipedia.org/wiki/WebSocket#Protocol_handshake

Going to close for now. Let me know if you need more help.
